### ISSUE TITLE
Misstar Tools 的原始安装脚本还有吗？

### ISSUE THREAD

**Issue by luzhaohui** [carabob/tools#1]
重新刷了小米的固件，现在 www.misstar.com 已经无法访问了，原来的脚本也就无法安装了。请问，还有什么办法吗？

**Comment by carabob** [comment]
`wget http://www.misstar.com/tools/appstore/install.sh -O /tmp/install.sh && chmod a+x /tmp/install.sh && /tmp/install.sh `

**Comment by luzhaohui** [comment]
這個命令無法執行了，無法獲取腳步

**Comment by carabob** [comment]
刚刚测试，没有问题。

**Comment by luzhaohui** [comment]
還真是，真奇怪，看來是不穩定造成的，謝謝已經 OK 了。謝謝
